# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChart, QLineSeries, QAreaSeries, QChartView
from PyQt5.QtCore import Qt

stylesheet = '''
QWidget #tab, #monitoring_tab, #keyboard_tab {;
    background-repeat: no-repeat;
    background-position: top center;
    background-color: #252525;
}
QGroupBox {
    color: blue;
    font: bold;
    border: 1px solid silver;
    border-radius: 6px;
    margin-top: 6px;
}

QGroupBox #monitoring_box {
    border: 0px dotted gray;
    margin: 0 0 0 0;
    /* background-color: yellow; */
}

QGroupBox #powerStatusLabel, #batteryStatusLabel, #batteryChargeLimitLabel, #nitroModeLabel, #cpuTempLabel, #gpuTempLabel, #sysTempLabel, #cpuFanSpeedLabel, #gpuFanSpeedLabel, #voltageLabel, #voltageMinMaxLabel, #voltageAverageLabel, #mode_label, #zone_label, #speed_label, #brightness_label, #direction_label {
    color: gray;
}
QGroupBox::title {
    subcontrol-origin: margin;
    subcontrol-position: top center;
    color: white;
}
'''


class CustomChart:
    def __init__(
        self,
        title="Voltage Chart",
        objectName="cusChart",
        sample_count=64,
        area_series_color="#80FF0000",
        line_series_color="#E74C3C",
        axis_x_label="Samples",
        axis_y_label="Voltage",
        axis_x_range=(0, 64),
        axis_y_range=(0.7, 1.6),
        **chart_kwargs,
    ):
        print(title, objectName, sample_count, area_series_color,
              line_series_color, axis_x_label, axis_y_label, axis_x_range, axis_y_range)
        self.samples = [0.0] * sample_count
        self.sample_count = sample_count
        self.axis_y_range = axis_y_range

        # Create chart elements
        self.chart = QChart()
        self.chartView = QChartView(self.chart)
        self.upperSeries = QLineSeries()
        self.lowerSeries = QLineSeries()
        self.areaSeries = QAreaSeries(self.upperSeries, self.lowerSeries)
        self.lineSeries = QLineSeries()
        self.lineSeriesShadow = QLineSeries()

        # Add series to chart
        self.chart.addSeries(self.areaSeries)
        self.chart.addSeries(self.lineSeries)
        self.chart.addSeries(self.lineSeriesShadow)

        # Customize chart appearance
        self.chart.setTheme(QChart.ChartThemeDark)
        self.chart.setBackgroundRoundness(0)
        self.chart.legend().hide()
        self.chart.createDefaultAxes()
        self.chart.setMargins(QtCore.QMargins(0, 0, 0, 0))
        self.chart.layout().setContentsMargins(0, 0, 0, 0)
        self.chart.setTitle(title)
        self.chart.setTitleFont(QtGui.QFont("Arial", 8))

        # Set series pen and brush colors
        # pen = QPen(Qt.white)
        # pen.setWidth(2)
        # self.areaSeries.setPen(pen)
        self.areaSeries.setBrush(QtGui.QColor(area_series_color))
        # self.areaSeries.setBrush(QtGui.QColor(255, 0, 0, 150))

        pen = self.lineSeries.pen()
        pen.setBrush(QtGui.QColor(line_series_color))
        pen.setStyle(Qt.PenStyle.DotLine)
        self.lineSeries.setPen(pen)

        # pen = self.lineSeriesShadow.pen()
        # pen.setBrush(QtGui.QColor(line_series_color))
        # # pen.setStyle(Qt.PenStyle.DotLine)
        # self.lineSeriesShadow.setPen(pen)
        # self.lineSeriesShadow.setPointLabelsFont(QtGui.QFont("Arial", 6))

        # Set axis labels and ranges
        axis_x = self.chart.axes(QtCore.Qt.Horizontal)[0]
        axis_x.setTitleText(axis_x_label)
        axis_x.setRange(*axis_x_range)
        # axis_x.setLabelsVisible(False)
        axis_x.setLabelsFont(QtGui.QFont("Arial", 6))
        axis_x.setTickCount(int(sample_count / 4))

        axis_y = self.chart.axes(QtCore.Qt.Vertical)[0]
        axis_y.setTitleText(axis_y_label)
        axis_y.setRange(*axis_y_range)
        axis_y.setLabelsFont(QtGui.QFont("Arial", 6))
        axis_y.setTickCount(4)  # Set how many tick lines you want to see

        # Apply additional chart customizations
        for key, value in chart_kwargs.items():
            setattr(self.chart, key, value)

        self.chartView.setObjectName(objectName)
        self.chartView.setRenderHint(QtGui.QPainter.Antialiasing)

        self.lineSeriesShadow.setPointLabelsVisible(True)
        self.lineSeriesShadow.setPointLabelsClipping(False)
        self.lineSeriesShadow.setPointLabelsFormat("@yPoint")
        # self.lineSeriesShadow.setPointLabelsFormat("%.2f" % 9)
        # self.lineSeriesShadow.setLabelPosition(QPointF(10, 10))
        # self.lineSeriesShadow.setLabelOverlap(False)

    def update_data(self, sample):
        if len(self.samples) >= self.sample_count-1:
            self.samples.pop(0)
        self.samples.append(sample)
        # print(self.samples)

        self.upperSeries.clear()
        self.lowerSeries.clear()
        for i, value in enumerate(self.samples):
            self.upperSeries.append(i, value)
            self.lowerSeries.append(i, 0)

        # HACK - to prevent chart redraw from clipping labels.
        #         Add 1 additional sample point to the end of the list whos y axis value
        #         is greater than the max chart range. This enables the repaint to not
        #         clip series labels whos y value > y max. The 1.2 part will help prevent labels
        #         being cut off when graphs reach the max y range.
        self.upperSeries.append(i+1, self.axis_y_range[1]*1.2)
        self.lowerSeries.append(i+1, 0)

        self.lineSeries.clear()
        # self.lineSeries.append(QPointF(0, sample))
        # self.lineSeries.append(QPointF(self.sample_count - 1, sample))
        self.lineSeries.append(0, sample)
        self.lineSeries.append(self.sample_count - 1, sample)

        self.lineSeriesShadow.clear()
        self.lineSeriesShadow.append(20, sample)


class Ui_NitroSense(object):

    WIDTH = 480
    HEIGHT = 680

    def setupUI(self, NitroSense):

        # Create window
        NitroSense.setObjectName("NitroSense")
        NitroSense.setWindowTitle("Nitro Sense™")
        NitroSense.setWindowModality(QtCore.Qt.NonModal)
        # NitroSense.resize(self.WIDTH, self.HEIGHT)

        ## -------Fan Control Tab--------##

        # QtGui.QFontDatabase.addApplicationFont("fonts/Squares Regular.otf")
        font = QtGui.QFont()
        # print(font.defaultFamily())
        font.setFamily("TT Squares")
        font.setWeight(QtGui.QFont.Light)

        boldfont = QtGui.QFont()
        boldfont.setFamily("DejaVu Sans")
        boldfont.setWeight(QtGui.QFont.Black)
        # boldfont.setPointSize(12)

        self.fan_control_tab = QtWidgets.QTabWidget(NitroSense)
        self.fan_control_tab.setGeometry(
            QtCore.QRect(0, 0, self.WIDTH, self.HEIGHT))
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.fan_control_tab.sizePolicy().hasHeightForWidth())
        # self.fan_control_tab.setSizePolicy(sizePolicy)
        self.fan_control_tab.setFont(font)
        self.fan_control_tab.setAccessibleName("Nitro Sense")
        self.fan_control_tab.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget(NitroSense)
        self.tab.setGeometry(QtCore.QRect(0, 0, self.WIDTH, self.HEIGHT))
        self.tab.setObjectName("tab")

        self.keyboard_tab = QtWidgets.QWidget(NitroSense)
        self.keyboard_tab.setObjectName("keyboard_tab")

        self.monitoring_tab = QtWidgets.QWidget(NitroSense)
        self.monitoring_tab.setGeometry(QtCore.QRect(0, 0, self.WIDTH, self.HEIGHT))
        self.monitoring_tab.setObjectName("monitoring_tab")

        # Tab name
        self.fan_control_tab.addTab(self.tab, "Home")
        self.fan_control_tab.addTab(self.keyboard_tab, "Keyboard")
        self.fan_control_tab.addTab(self.monitoring_tab, "Monitoring")

        self.tab.setStyleSheet(stylesheet)
        self.keyboard_tab.setStyleSheet(stylesheet)
        self.monitoring_tab.setStyleSheet(stylesheet)

        ## ------------Status-------------##

        self.status_box = QtWidgets.QGroupBox(self.tab)
        self.status_box.setGeometry(QtCore.QRect(20, 40, 340, 100))
        self.status_box.setFont(boldfont)
        self.status_box.setObjectName("status_box")

        # POWERSTATUS
        self.powerStatusLabel = QtWidgets.QLabel(self.status_box)
        self.powerStatusLabel.setObjectName("powerStatusLabel")
        self.powerStatusLabel.setText("Power Status  :")
        self.powerStatusLabel.move(10, 15)
        self.powerStatusValue = QtWidgets.QLabel(self.status_box)
        self.powerStatusValue.setObjectName("powerStatusValue")
        self.powerStatusValue.move(125, 15)

        # BATTERYSTATUS
        self.batteryStatusLabel = QtWidgets.QLabel(self.status_box)
        self.batteryStatusLabel.setObjectName("batteryStatusLabel")
        self.batteryStatusLabel.setText("Battery Status:")
        self.batteryStatusLabel.move(10, 35)
        self.batteryStatusValue = QtWidgets.QLabel(self.status_box)
        self.batteryStatusValue.setObjectName("batteryStatusValue")
        self.batteryStatusValue.move(125, 35)

        # BATTERYCHARGELIMIT
        self.batteryChargeLimitLabel = QtWidgets.QLabel(self.status_box)
        self.batteryChargeLimitLabel.setObjectName("batteryChargeLimitLabel")
        self.batteryChargeLimitLabel.setText("Charge Limit   :")
        self.batteryChargeLimitLabel.move(10, 55)
        self.batteryChargeLimitValue = QtWidgets.QLabel(self.status_box)
        self.batteryChargeLimitValue.setObjectName("batteryChargeLimitValue")
        self.batteryChargeLimitValue.move(125, 55)

        # NITROMODE
        self.nitroModeLabel = QtWidgets.QLabel(self.status_box)
        self.nitroModeLabel.setObjectName("nitroModeLabel")
        self.nitroModeLabel.setText("Nitro Mode:")
        self.nitroModeLabel.move(10, 75)
        self.nitroModeValue = QtWidgets.QLabel(self.status_box)
        self.nitroModeValue.setObjectName("nitroModeValue")
        self.nitroModeValue.move(125, 75)
        self.nitroModeValue.setText("Extreme")

        self.powerStatusLabel.setFont(boldfont)
        self.batteryStatusLabel.setFont(boldfont)
        self.batteryChargeLimitLabel.setFont(boldfont)
        self.nitroModeLabel.setFont(boldfont)


        self.powerStatusValue.setFont(font)
        self.batteryStatusValue.setFont(font)
        self.batteryChargeLimitValue.setFont(font)
        self.nitroModeValue.setFont(font)


        ## ---------Nitro Mode---------##

        self.predMode = QtWidgets.QGroupBox(self.tab)
        self.predMode.setGeometry(QtCore.QRect(370, 40, 90, 100))
        self.predMode.setFont(boldfont)
        self.predMode.setObjectName("predMode")

        self.quietModeCB = QtWidgets.QRadioButton(self.predMode)
        self.quietModeCB.setFont(font)
        self.quietModeCB.setObjectName("quietModeCB")
        self.quietModeCB.move(10, 15)

        self.defaultModeCB = QtWidgets.QRadioButton(self.predMode)
        self.defaultModeCB.setFont(font)
        self.defaultModeCB.setObjectName("defaultModeCB")
        self.defaultModeCB.move(10, 35)

        self.extremeModeCB = QtWidgets.QRadioButton(self.predMode)
        self.extremeModeCB.setFont(font)
        self.extremeModeCB.setObjectName("extremeModeCB")
        self.extremeModeCB.move(10, 55)

        ## -------------Misc--------------##

        self.KB_box = QtWidgets.QGroupBox(self.tab)
        self.KB_box.setGeometry(QtCore.QRect(320, 145, 140, 80))
        self.KB_box.setFont(boldfont)
        self.KB_box.setObjectName("KB_box")

        self.KBTimerCB = QtWidgets.QCheckBox(self.KB_box)
        self.KBTimerCB.setFont(font)
        self.KBTimerCB.setObjectName("global_KBTimer")
        self.KBTimerCB.move(10, 10)

        self.usbChargingCB = QtWidgets.QCheckBox(self.KB_box)
        self.usbChargingCB.setFont(font)
        self.usbChargingCB.setObjectName("usbCharging")
        self.usbChargingCB.move(10, 40)

        self.chargeLimit = QtWidgets.QCheckBox(self.KB_box)
        self.chargeLimit.setFont(font)
        self.chargeLimit.setObjectName("ChargeLimit")
        self.chargeLimit.move(10, 55)

        ## --------Temperatures----------##

        self.temp_box = QtWidgets.QGroupBox(self.tab)
        self.temp_box.setGeometry(QtCore.QRect(20, 145, 140, 80))
        self.temp_box.setFont(boldfont)
        self.temp_box.setObjectName("temp_box")

        self.cpuTempLabel = QtWidgets.QLabel(self.temp_box)
        self.cpuTempLabel.setObjectName("cpuTempLabel")
        self.cpuTempLabel.setText("CPU:")
        self.cpuTempLabel.move(10, 15)
        self.cpuTempValue = QtWidgets.QLabel(self.temp_box)
        self.cpuTempValue.setObjectName("cpuTempValue")
        self.cpuTempValue.setFont(font)
        self.cpuTempValue.move(60, 15)

        self.gpuTempLabel = QtWidgets.QLabel(self.temp_box)
        self.gpuTempLabel.setObjectName("gpuTempLabel")
        self.gpuTempLabel.setText("GPU:")
        self.gpuTempLabel.move(10, 35)
        self.gpuTempValue = QtWidgets.QLabel(self.temp_box)
        self.gpuTempValue.setObjectName("gpuTempValue")
        self.gpuTempValue.move(60, 35)

        self.sysTempLabel = QtWidgets.QLabel(self.temp_box)
        self.sysTempLabel.setObjectName("sysTempLabel")
        self.sysTempLabel.setText("SYS:")
        self.sysTempLabel.move(10, 55)
        self.sysTempValue = QtWidgets.QLabel(self.temp_box)
        self.sysTempValue.setObjectName("sysTempValue")
        self.sysTempValue.move(60, 55)

        self.cpuTempLabel.setFont(boldfont)
        self.gpuTempLabel.setFont(boldfont)
        self.sysTempLabel.setFont(boldfont)

        self.cpuTempValue.setFont(font)
        self.gpuTempValue.setFont(font)
        self.sysTempValue.setFont(font)

        ## -----------Fan RPM------------##

        self.fan_box = QtWidgets.QGroupBox(self.tab)
        self.fan_box.setGeometry(QtCore.QRect(170, 145, 140, 80))
        self.fan_box.setFont(boldfont)
        self.fan_box.setObjectName("fan_box")

        self.cpuFanSpeedLabel = QtWidgets.QLabel(self.fan_box)
        self.cpuFanSpeedLabel.setObjectName("cpuFanSpeedLabel")
        self.cpuFanSpeedLabel.setText("CPU:\t")
        self.cpuFanSpeedLabel.move(10, 15)
        self.cpuFanSpeedValue = QtWidgets.QLabel(self.fan_box)
        self.cpuFanSpeedValue.setObjectName("cpuFanSpeedValue")
        self.cpuFanSpeedValue.move(50, 15)

        self.gpuFanSpeedLabel = QtWidgets.QLabel(self.fan_box)
        self.gpuFanSpeedLabel.setObjectName("gpuFanSpeedLabel")
        self.gpuFanSpeedLabel.setText("GPU:\t")
        self.gpuFanSpeedLabel.move(10, 35)
        self.gpuFanSpeedValue = QtWidgets.QLabel(self.fan_box)
        self.gpuFanSpeedValue.setObjectName("gpuFanSpeedValue")
        self.gpuFanSpeedValue.move(50, 35)

        self.cpuFanSpeedLabel.setFont(boldfont)
        self.gpuFanSpeedLabel.setFont(boldfont)

        self.cpuFanSpeedValue.setFont(font)
        self.gpuFanSpeedValue.setFont(font)

        ## ----------Undervolt-----------##

        self.undervolt_box = QtWidgets.QGroupBox(self.tab)
        self.undervolt_box.setGeometry(QtCore.QRect(20, 230, 440, 200))
        self.undervolt_box.setFont(boldfont)
        self.undervolt_box.setObjectName("undervolt_box")

        self.undervoltLayout = QtWidgets.QVBoxLayout(self.undervolt_box)
        self.undervoltLayout.setContentsMargins(10, 30, 10, 10)
        self.undervoltLayout.setObjectName("undervoltLayout")

        # Current voltage
        self.voltageLabel = QtWidgets.QLabel(self.undervolt_box)
        self.voltageLabel.setText("Voltage:")
        self.voltageLabel.setObjectName("voltageLabel")
        self.voltageLabel.move(10, 10)

        self.voltageValue = QtWidgets.QLabel(self.undervolt_box)
        self.voltageValue.setObjectName("voltageValue")
        self.voltageValue.move(75, 10)

        # Max / Min
        self.voltageMinMaxLabel = QtWidgets.QLabel(self.undervolt_box)
        self.voltageMinMaxLabel.setText("Min / Max:")
        self.voltageMinMaxLabel.setObjectName("voltageMinMaxLabel")
        self.voltageMinMaxLabel.move(150, 10)

        self.voltageMinMaxValue = QtWidgets.QLabel(self.undervolt_box)
        self.voltageMinMaxValue.setObjectName("voltageMinMaxValue")
        self.voltageMinMaxValue.move(230, 10)

        # Undervolt readings
        self.undervoltStatus = QtWidgets.QTextBrowser(self.undervolt_box)
        self.undervoltStatus.setObjectName("undervoltStatus")
        self.undervoltLayout.addWidget(self.undervoltStatus)

        self.voltageLabel.setFont(boldfont)
        self.voltageMinMaxLabel.setFont(boldfont)

        self.undervoltStatus.setFont(font)
        self.voltageValue.setFont(font)
        self.voltageMinMaxValue.setFont(font)

        ## ------------Global------------##

        self.global_box = QtWidgets.QGroupBox(self.tab)
        self.global_box.setGeometry(QtCore.QRect(200, 505, 80, 80))
        self.global_box.setFont(boldfont)
        self.global_box.setObjectName("global_box")

        self.globallayoutWidget = QtWidgets.QWidget(self.global_box)
        self.globallayoutWidget.setGeometry(QtCore.QRect(10, 20, 100, 50))
        self.globallayoutWidget.setObjectName("globallayoutWidget")
        self.horizontalLayout = QtWidgets.QVBoxLayout(self.globallayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)

        self.global_auto = QtWidgets.QRadioButton(self.globallayoutWidget)
        self.global_auto.setFont(font)
        self.global_auto.setChecked(True)
        self.global_auto.setObjectName("global_auto")
        self.horizontalLayout.addWidget(self.global_auto)

        self.global_turbo = QtWidgets.QRadioButton(self.globallayoutWidget)
        self.global_turbo.setFont(font)
        self.global_turbo.setObjectName("global_turbo")
        self.horizontalLayout.addWidget(self.global_turbo)

        ## ----------CPU Box-------------##

        self.cpu_box = QtWidgets.QGroupBox(self.tab)
        self.cpu_box.setGeometry(QtCore.QRect(20, 440, 150, 190))
        self.cpu_box.setFont(boldfont)
        self.cpu_box.setObjectName("cpu_box")

        self.cpulayoutWidget = QtWidgets.QWidget(self.cpu_box)
        self.cpulayoutWidget.setGeometry(QtCore.QRect(10, 40, 100, 100))
        self.cpulayoutWidget.setObjectName("cpulayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cpulayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cpu_auto = QtWidgets.QRadioButton(self.cpulayoutWidget)
        self.cpu_auto.setChecked(True)
        self.cpu_auto.setObjectName("cpu_auto")
        self.verticalLayout.addWidget(self.cpu_auto)
        self.cpu_manual = QtWidgets.QRadioButton(self.cpulayoutWidget)
        self.cpu_manual.setObjectName("cpu_manual")
        self.verticalLayout.addWidget(self.cpu_manual)
        self.cpu_turbo = QtWidgets.QRadioButton(self.cpulayoutWidget)
        self.cpu_turbo.setObjectName("cpu_turbo")
        self.verticalLayout.addWidget(self.cpu_turbo)
        self.cpuManualSlider = QtWidgets.QSlider(self.cpu_box)
        self.cpuManualSlider.setEnabled(False)
        self.cpuManualSlider.setGeometry(QtCore.QRect(110, 20, 20, 160))
        # self.cpuManualSlider.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))

        self.cpuManualSlider.setTickInterval(1)
        self.cpuManualSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)

        self.cpuManualSlider.setMaximum(10)
        self.cpuManualSlider.setProperty("value", 3)
        self.cpuManualSlider.setOrientation(QtCore.Qt.Vertical)
        self.cpuManualSlider.setObjectName("cpuManualSlider")

        self.cpu_auto.setFont(font)
        self.cpu_manual.setFont(font)
        self.cpu_turbo.setFont(font)

        ## ----------GPU Box-------------##

        self.gpu_box = QtWidgets.QGroupBox(self.tab)
        self.gpu_box.setGeometry(QtCore.QRect(310, 440, 150, 190))
        self.gpu_box.setFont(boldfont)
        self.gpu_box.setObjectName("gpu_box")

        self.gpulayoutWidget = QtWidgets.QWidget(self.gpu_box)
        self.gpulayoutWidget.setGeometry(QtCore.QRect(10, 40, 100, 100))
        self.gpulayoutWidget.setObjectName("gpulayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gpulayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gpu_auto = QtWidgets.QRadioButton(self.gpulayoutWidget)
        self.gpu_auto.setChecked(True)
        self.gpu_auto.setObjectName("gpu_auto")
        self.verticalLayout_2.addWidget(self.gpu_auto)
        self.gpu_manual = QtWidgets.QRadioButton(self.gpulayoutWidget)
        self.gpu_manual.setObjectName("gpu_manual")
        self.verticalLayout_2.addWidget(self.gpu_manual)
        self.gpu_turbo = QtWidgets.QRadioButton(self.gpulayoutWidget)
        self.gpu_turbo.setObjectName("gpu_turbo")
        self.verticalLayout_2.addWidget(self.gpu_turbo)
        self.gpuManualSlider = QtWidgets.QSlider(self.gpu_box)
        self.gpuManualSlider.setEnabled(False)
        self.gpuManualSlider.setGeometry(QtCore.QRect(110, 20, 20, 160))
        # self.gpuManualSlider.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))

        self.gpuManualSlider.setTickInterval(1)
        self.gpuManualSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)

        self.gpuManualSlider.setMaximum(10)
        self.gpuManualSlider.setProperty("value", 3)
        # self.gpuManualSlider.setSliderPosition(3)
        self.gpuManualSlider.setOrientation(QtCore.Qt.Vertical)
        self.gpuManualSlider.setObjectName("gpuManualSlider")

        self.gpu_auto.setFont(font)
        self.gpu_manual.setFont(font)
        self.gpu_turbo.setFont(font)

        ## ------------------------------##

        self.exit_button = QtWidgets.QPushButton(self.tab)
        self.exit_button.setGeometry(QtCore.QRect(int(self.WIDTH/2-25), 600, 50, 25))
        self.exit_button.setFont(boldfont)
        self.exit_button.setObjectName("pushButton")
        self.exit_button.setText("Exit")

        # self.reset_button = QtWidgets.QPushButton(self.tab)
        # self.reset_button.setGeometry(QtCore.QRect(int(self.WIDTH/2-40), 440, 80, 25))
        # self.reset_button.setFont(font)
        # self.reset_button.setObjectName("restPushButton")
        # self.reset_button.setText("Reset")

        # Undervolt selection dropdown with 100mv steps from 0mv to 600mv
        self.undervolt_dropdown = QtWidgets.QComboBox(self.tab)
        self.undervolt_dropdown.setGeometry(
            QtCore.QRect(int(self.WIDTH/2-40), 440, 80, 25))
        self.undervolt_dropdown.setFont(font)
        self.undervolt_dropdown.setObjectName("undervoltComboBox")
        self.undervolt_dropdown.addItems(
            ["0mV", "-100mV", "-200mV", "-300mV", "-400mV", "-500mV", "-600mV", "-700mV"])

        self.undervolt_button = QtWidgets.QPushButton(self.tab)
        self.undervolt_button.setGeometry(
            QtCore.QRect(int(self.WIDTH/2-40), 465, 80, 25))
        self.undervolt_button.setFont(font)
        self.undervolt_button.setObjectName("undervoltPushButton")
        self.undervolt_button.setText("Undervolt")

        ## --------KEYBOARD TAB--------##
        

        ## --------MONITORING TAB--------##

        self.voltageChart = CustomChart(
            "Voltage", "voltage_box", 64, "#80ff0000", "#E74C3C", "", "", (0, 63), (0.7, 1.6))
        self.cpuChart = CustomChart(
            "CPU Temp", "cpuchart_box", 64, "#800000ff", "#0E86D4", "", "", (0, 63), (0, 110))
        self.gpuChart = CustomChart(
            "GPU Temp", "gpuchart_box", 64, "#8000ff00", "#0E8600", "", "", (0, 63), (0, 110))
        self.sysChart = CustomChart(
            "SYS Temp", "syschart_box", 64, "#8000ffff", "#0Effff", "", "", (0, 63), (0, 110))

        self.cpuFanChart = CustomChart(
            "CPU Fan", "cpufanchart_box", 64, "#800080ff", "#0E80ff", "", "", (0, 63), (0, 7700))
        self.gpuFanChart = CustomChart(
            "GPU Fan", "gpufanchart_box", 64, "#8000ff80", "#0Eff80", "", "", (0, 63), (0, 7700))

        # Set up chart layout
        # self.chart_box = QtWidgets.QGroupBox(self.tab)
        self.chart_box = QtWidgets.QGroupBox(self.monitoring_tab)
        self.chart_box.setGeometry(QtCore.QRect(0, 0, self.WIDTH, self.HEIGHT-30))
        self.chart_box.setObjectName("monitoring_box")

        self.vchart = QtWidgets.QVBoxLayout(self.chart_box)
        # self.vchart.addStretch()
        self.vchart.setSpacing(0)
        self.vchart.setContentsMargins(0, 0, 0, 0)
        self.vchart.addWidget(self.voltageChart.chartView)
        self.vchart.addWidget(self.cpuChart.chartView)
        self.vchart.addWidget(self.gpuChart.chartView)
        self.vchart.addWidget(self.sysChart.chartView)
        self.vchart.addWidget(self.cpuFanChart.chartView)
        self.vchart.addWidget(self.gpuFanChart.chartView)
        self.chart_box.setLayout(self.vchart)


        self.global_turbo.clicked['bool'].connect(self.cpu_turbo.setChecked)
        self.global_turbo.clicked['bool'].connect(self.gpu_turbo.setChecked)
        self.global_auto.clicked['bool'].connect(self.cpu_auto.setChecked)
        self.global_auto.clicked['bool'].connect(self.gpu_auto.setChecked)

        self.cpu_manual.toggled['bool'].connect(
            self.cpuManualSlider.setEnabled)
        self.gpu_manual.toggled['bool'].connect(
            self.gpuManualSlider.setEnabled)

        # Prevents the user from disabling max cpu or gpu fan mode individually when global turbo mode is enabled
        self.global_turbo.toggled['bool'].connect(self.cpu_auto.setDisabled)
        self.global_turbo.toggled['bool'].connect(self.cpu_manual.setDisabled)
        self.global_turbo.toggled['bool'].connect(self.gpu_auto.setDisabled)
        self.global_turbo.toggled['bool'].connect(self.gpu_manual.setDisabled)

        # A hacky solution: eliminates the need for turbo button to listen to cpu and gpu buttons at the same time
        # self.cpu_turbo.toggled['bool'].connect(self.gpu_turbo.setDisabled)
        # self.gpu_turbo.toggled['bool'].connect(self.cpu_turbo.setDisabled)

        # QtCore.QMetaObject.connectSlotsByName(NitroSense)

        # ----------------------------------------------------
        # Set button text and window titles

        # Window title
        NitroSense.setWindowTitle("Linux NitroSense")

        # CoolBoost checkbox
        # self.coolboost_checkbox.setToolTip(_translate("NitroSense", "Only Works When In Auto Mode"))
        # self.coolboost_checkbox.setText(_translate("NitroSense", "CoolBoost™"))

        # Power Status
        self.powerStatusValue.setText("0")
        self.batteryStatusValue.setText("Battery Not In Use")
        self.batteryChargeLimitValue.setText("Off")
        self.nitroModeValue.setText("Default")

        self.predMode.setTitle("Mode")
        self.quietModeCB.setText("Quiet")
        self.defaultModeCB.setText("Default")
        self.extremeModeCB.setText("Extreme")

        # Fan box
        self.fan_box.setTitle("Fan RPM")

        # Temp box
        self.temp_box.setTitle("Temps")

        self.cpuFanSpeedValue.setText("5660" + " RPM")
        self.gpuFanSpeedValue.setText("5660" + " RPM")
        self.cpuTempValue.setText("100" + "°")
        self.gpuTempValue.setText("100" + "°")
        self.sysTempValue.setText("100" + "°")

        # Misc box
        self.KB_box.setTitle("Misc")
        self.KBTimerCB.setText("KB Timeout")
        # self.trackpadCB.setText("Disable Trackpad")
        self.usbChargingCB.setText("USB Charging")
        self.chargeLimit.setText("Charge Limit")

        # Status box
        self.status_box.setTitle("Status")

        # Undervolt box
        self.undervolt_box.setTitle("Undervolt")

        self.voltageValue.setText("0.00")
        self.voltageMinMaxValue.setText("0.00")

        # Global box
        self.global_box.setTitle("Global")
        self.global_auto.setText("Auto")
        self.global_turbo.setText("Turbo")

        # CPU box
        self.cpu_box.setTitle("CPU Fan")
        self.cpu_auto.setText("Auto")
        self.cpu_manual.setText("Manual")
        self.cpu_turbo.setText("Max speed")

        # GPU box
        self.gpu_box.setTitle("GPU Fan")
        self.gpu_auto.setText("Auto")
        self.gpu_manual.setText("Manual")
        self.gpu_turbo.setText("Max speed")

        # Keyboard tab
        self.keyboard_box = QtWidgets.QGroupBox(self.keyboard_tab)
        self.keyboard_box.setGeometry(QtCore.QRect(20, 20, 440, 610))
        self.keyboard_box.setFont(boldfont)
        self.keyboard_box.setObjectName("keyboard_box")
        self.keyboard_box.setTitle("Keyboard")

        self.centralwidget = QtWidgets.QWidget(self.keyboard_box)
        self.centralwidget.setObjectName("centralwidget")

        self.mode_label = QtWidgets.QLabel(self.keyboard_box)
        self.mode_label.setGeometry(QtCore.QRect(20, 20, 100, 30))
        self.mode_label.setObjectName("mode_label")
        self.mode_label.setText("Mode:")

        self.mode_combo = QtWidgets.QComboBox(self.keyboard_box)
        self.mode_combo.setGeometry(QtCore.QRect(self.WIDTH - 150 - 60, 20, 150, 30))
        self.mode_combo.setObjectName("mode_combo")
        self.mode_combo.addItems(["Static", "Breath", "Neon", "Wave", "Shifting", "Zoom"])

        self.zone_label = QtWidgets.QLabel(self.keyboard_box)
        self.zone_label.setGeometry(QtCore.QRect(20, 60, 100, 30))
        self.zone_label.setObjectName("zone_label")
        self.zone_label.setText("Zone:")

        self.zone_combo = QtWidgets.QComboBox(self.keyboard_box)
        self.zone_combo.setGeometry(QtCore.QRect(self.WIDTH - 150 - 60, 60, 150, 30))
        self.zone_combo.setObjectName("zone_combo")
        self.zone_combo.addItems(["all", "1", "2", "3", "4"])

        self.speed_label = QtWidgets.QLabel(self.keyboard_box)
        self.speed_label.setGeometry(QtCore.QRect(20, 100, 100, 30))
        self.speed_label.setObjectName("speed_label")
        self.speed_label.setText("Speed:")

        self.speed_spin = QtWidgets.QSlider(self.keyboard_box)
        self.speed_spin.setGeometry(QtCore.QRect(self.WIDTH - 150 - 60, 100, 150, 30))
        self.speed_spin.setObjectName("speed_spin")
        self.speed_spin.setOrientation(QtCore.Qt.Horizontal)
        self.speed_spin.setRange(0, 9)
        self.speed_spin.setTickInterval(1)

        self.brightness_label = QtWidgets.QLabel(self.keyboard_box)
        self.brightness_label.setGeometry(QtCore.QRect(20, 140, 100, 30))
        self.brightness_label.setObjectName("brightness_label")
        self.brightness_label.setText("Brightness:")

        self.brightness_spin = QtWidgets.QSlider(self.keyboard_box)
        self.brightness_spin.setGeometry(QtCore.QRect(self.WIDTH - 150 - 60, 140, 150, 30))
        self.brightness_spin.setObjectName("brightness_spin")
        self.brightness_spin.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_spin.setRange(0, 100)
        self.brightness_spin.setTickInterval(1)

        self.direction_label = QtWidgets.QLabel(self.keyboard_box)
        self.direction_label.setGeometry(QtCore.QRect(20, 180, 100, 30))
        self.direction_label.setObjectName("direction_label")
        self.direction_label.setText("Direction:")

        self.direction_combo = QtWidgets.QComboBox(self.keyboard_box)
        self.direction_combo.setGeometry(QtCore.QRect(self.WIDTH - 150 - 60, 180, 150, 30))
        self.direction_combo.setObjectName("direction_combo")
        self.direction_combo.addItems(["Left to right", "Right to left"])

        self.color_button = QtWidgets.QPushButton(self.keyboard_box)
        self.color_button.setGeometry(QtCore.QRect(self.WIDTH - 100 - 60, 220, 100, 30))
        self.color_button.setObjectName("color_button")
        self.color_button.setText("Select Color")
        self.load_button = QtWidgets.QPushButton(self.keyboard_box)
        self.load_button.setGeometry(QtCore.QRect(20, 560, 120, 30))
        self.load_button.setObjectName("load_button")
        self.load_button.setText("Load")

        self.apply_button = QtWidgets.QPushButton(self.keyboard_box)
        # self.apply_button.setGeometry(QtCore.QRect(130, 560, 100, 30))
        self.apply_button.setGeometry(QtCore.QRect(self.WIDTH - 120 - 60, 560, 120, 30))
        self.apply_button.setObjectName("apply_button")
        self.apply_button.setText("Apply")

        self.save_button = QtWidgets.QPushButton(self.keyboard_box)
        # self.save_button.setGeometry(QtCore.QRect(240, 560, 100, 30))
        self.save_button.setGeometry(QtCore.QRect(self.WIDTH - 60 - 120 - 120 - 20, 560, 120, 30))
        self.save_button.setObjectName("save_button")
        self.save_button.setText("Save")

        self.mode_label.setFont(boldfont)
        self.zone_label.setFont(boldfont)
        self.speed_label.setFont(boldfont)
        self.brightness_label.setFont(boldfont)
        self.direction_label.setFont(boldfont)

        self.mode_combo.setFont(font)
        self.zone_combo.setFont(font)
        self.speed_spin.setFont(font)
        self.brightness_spin.setFont(font)
        self.direction_combo.setFont(font)
        self.color_button.setFont(font)
        self.apply_button.setFont(font)
        self.save_button.setFont(font)
        self.load_button.setFont(font)
